/**
 * storageService.ts
 * Handles file uploads and downloads via presigned S3 URLs.
 * Presigned URLs are generated by the Lambda /upload endpoint — no AWS
 * credentials are ever held on the frontend.
 */

import { post } from './apiService';

// ─── Types ────────────────────────────────────────────────────────────────────

export type UploadType = 'voice' | 'media' | 'avatar';

export interface PresignedUrlRequest {
    fileName: string;
    fileType: string;
    uploadType: UploadType;
}

export interface PresignedUrlResponse {
    uploadUrl: string;   // PUT to this URL
    downloadUrl: string; // Public/presigned GET URL after upload
    key: string;         // S3 object key
}

// ─── Get presigned URL from Lambda ───────────────────────────────────────────

export async function getPresignedUrl(
    request: PresignedUrlRequest,
): Promise<PresignedUrlResponse> {
    const { data } = await post<PresignedUrlRequest, PresignedUrlResponse>(
        '/upload',
        request,
    );
    return data;
}

// ─── Upload a local file URI to S3 via presigned URL ─────────────────────────

/**
 * Uploads a file from a local URI (expo-file-system / camera roll) to S3.
 *
 * @param localUri   - `file://...` URI from expo-file-system or camera
 * @param fileName   - Desired S3 key name (e.g. "recording_2024.m4a")
 * @param mimeType   - MIME type (e.g. "audio/m4a", "image/jpeg")
 * @param uploadType - Logical bucket folder ("voice" | "media" | "avatar")
 * @returns          - The public/presigned download URL
 */
export async function uploadFile(
    localUri: string,
    fileName: string,
    mimeType: string,
    uploadType: UploadType = 'media',
): Promise<string> {
    // 1. Get presigned PUT URL from Lambda
    const { uploadUrl, downloadUrl } = await getPresignedUrl({
        fileName,
        fileType: mimeType,
        uploadType,
    });

    // 2. Fetch the local file as a blob
    const fileResponse = await fetch(localUri);
    const blob = await fileResponse.blob();

    // 3. PUT the blob directly to S3 — no credentials needed
    const s3Response = await fetch(uploadUrl, {
        method: 'PUT',
        headers: { 'Content-Type': mimeType },
        body: blob,
    });

    if (!s3Response.ok) {
        throw new Error(`S3 upload failed: ${s3Response.status} ${s3Response.statusText}`);
    }

    return downloadUrl;
}

// ─── Download helper (returns blob URL) ──────────────────────────────────────

/**
 * Fetches a file from a presigned S3 GET URL and returns a local object URL.
 * Useful for previewing audio/images without re-uploading.
 */
export async function downloadFile(presignedGetUrl: string): Promise<string> {
    const response = await fetch(presignedGetUrl);
    if (!response.ok) {
        throw new Error(`S3 download failed: ${response.status}`);
    }
    const blob = await response.blob();
    return URL.createObjectURL(blob);
}
